### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by asaf**
Support react 0.14

### CODE REVIEW

**Comment by eudisd** [comment]
+1

**Comment by ninjasort** [comment]
Currently updating this in `v1.4.x`. On the way.

**Comment by eudisd** [comment]
Hey @cameronjroe any updates on this?

**Comment by ninjasort** [comment]
Had a nice smack in the face by the Babel 6 updates. Working on it..

**Comment by eudisd** [comment]
Thanks for the update @cameronjroe

**Comment by mattwoodco** [comment]
+1, thanks @cameronjroe

**Pull request closed without merging**
